env:
  NODE_VERSION: 20
jobs:
  excerpts:
    if: github.repository == 'flutter/website'
    name: Check if code excerpts are up to date
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        submodules: recursive
    - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
      with:
        sdk: stable
    - name: Fetch Dart dependencies
      run: dart pub get
    - continue-on-error: ${{ matrix.experimental }}
      name: Check if excerpts are up to date
      run: dart run flutter_site refresh-excerpts --fail-on-update
  firebase-validate:
    if: github.repository == 'flutter/website'
    name: Validate Firebase configuration
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        submodules: recursive
    - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
      with:
        sdk: stable
    - name: Fetch Dart dependencies
      run: dart pub get
    - name: Validate the firebase.json file
      run: dart run flutter_site verify-firebase-json
  linkcheck:
    name: Build site and check links
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        submodules: recursive
    - name: Enable Corepack
      run: corepack enable
    - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
      with:
        cache: pnpm
        node-version: ${{ env.NODE_VERSION }}
    - name: Setup pnpm
      run: corepack install
    - name: Install node dependencies
      run: pnpm install --frozen-lockfile
    - uses: dart-lang/setup-dart@f0ead981b4d9a35b37f30d36160575d60931ec30
      with:
        sdk: stable
    - name: Fetch Dart dependencies
      run: dart pub get
    - name: Build site
      run: dart run flutter_site build
    - name: Check for broken Markdown link references
      run: dart run flutter_site check-link-references
    - name: Check for broken internal links
      run: dart run flutter_site check-links
  test:
    if: github.repository == 'flutter/website'
    name: Analyze and test code examples
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - name: Collect Workflow Telemetry
      uses: Nfsaavedra/workflow-telemetry-action@raw_data
      with:
        save_raw_stats: true
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
      with:
        submodules: recursive
    - uses: subosito/flutter-action@f2c4f6686ca8e8d6e6d0f28410eeef506ed66aff
      with:
        channel: ${{ matrix.branch }}
    - name: Fetch Dart dependencies
      run: dart pub get
    - continue-on-error: ${{ matrix.experimental }}
      name: Check Dart code formatting
      run: dart run flutter_site format-dart --check
    - continue-on-error: ${{ matrix.experimental }}
      name: Analyze Dart code
      run: dart run flutter_site analyze-dart
    - continue-on-error: ${{ matrix.experimental }}
      name: Run Dart tests
      run: dart run flutter_site test-dart
    strategy:
      fail-fast: false
      matrix:
        include:
        - branch: beta
          experimental: true
          name: Beta channel
        - branch: stable
          experimental: false
          name: Stable channel
name: test
'on':
- workflow_dispatch
permissions: write-all
